version: '2'
services:
    bookster2-app:
        image: bookster2
        external_links:
            - bookster2-mysql:mysql
            - bookster2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookster2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    bookster2-mysql:
        extends:
            file: mysql.yml
            service: bookster2-mysql
    bookster2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bookster2-elasticsearch
